### ISSUE TITLE
EBD column headers changed

### ISSUE THREAD

**Issue by nmanich** [paintedstork/eBird-filter-generator#4]
the SUBNATIONAL headers changed a while back, which was making it hangup.  I think this fixes that, from ebdstrip file.

# Strip unwanted columns from eBird states
ebd_states    <- subset(ebd_states, select = c("STATE.CODE", "STATE"))

# Strip unwanted columns from eBird districts
ebd_districts <- subset(ebd_districts, select = c("COUNTY.CODE", "COUNTY"))

# Strip unwanted columns from eBird lists
ebd_lists <- subset(ebd_lists, select = c("STATE.CODE", "COUNTY.CODE", "OBSERVATION.DATE", "DURATION.MINUTES", "LONGITUDE", "LATITUDE", "UNIQUE_SAMPLING_ID", "ALL.SPECIES.REPORTED"))

**Comment by paintedstork** [comment]
I have fixed them with a few new updates to generate files per state (avoiding large files)
